lib: sky130_fd_sc_hd
widths: [32]
counts: [8, 32, 128, 512, 2048]
design_name_template: "RAM{count}"
variants:
  - null
rx_overrides:
  Block.floatbuf: "\\bFLOATBUF_B(\\d+)\\\\(\\d*)\\[(\\d+)\\\\]"
  Mux.mux: "\\bMUX(\\d+)\\\\\\[(\\d+)\\\\\\]"
  Word.byte: "\\bB(\\d+)\\b"